partition_alignments:
  - aln: example.phy
    prt: example.nex
#  - aln: d59_8.phy
#    prt: d59_8.nex

single_alignments:
  - example.phy
  - d59_8.phy

partition_options:
   - -sp
   - -spp

generic_options:
   - -m TEST

specific_test:
  # iqtree2 location is in the bin folder
  - cmd: -s test_data/example.phy -redo -sp test_data/example.nex
    keyword: "BEST SCORE FOUND :"
    EXPECT_LE: 10.2
  - cmd: -s test_data/example.phy -redo -sp test_data/example.nex
    keyword: "Total wall-clock time used:"
    EXPECT_GE: 10.1
  - cmd: -s test_data/example.phy -redo -sp test_data/example.nex
    keyword: "Total wall-clock time used:"
    EXPECT_GE: 1
    EXPECT_LE: 40
  - cmd: -s test_data/example.phy -redo -sp test_data/example.nex
    keyword: "Total wall-clock time used:"
    EXPECT_EQ: iqtree1 # category
    EXPECT_GE: 0.5
  - cmd: -s test_data/example.phy -redo -sp test_data/example.nex
    keyword: "Number of categories:"
    EXPECT_GE: 3
    EXPECT_LE: 5

